apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-buoyant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://helm.buoyant.cloud
    targetRevision: 0.34.0
    helm:
      values: >-
        license: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJCdW95YW50IEluYyIsInN1YiI6ImxpY2Vuc2UiLCJhdWQiOiJNSXJhZSBMYWJzIiwiZXhwIjo0MTAyNDQ0ODAwLCJDbGllbnRJRCI6InZFaVZBeU50UjBPNjhKYVkiLCJDbGllbnRTZWNyZXQiOiJjZGQzYmQ5ODI4ZjEwMTU4NWNjNzYxMmNlMGFkODY2MzhmZTU4NWM5ZTI1MDJmMGU4MzIyZjJhMjYwNTRkYmM4IiwiUHJvZHVjdCI6IkJFTCIsIlZlcnNpb24iOjIsIk1hbmFnZWRDb250cm9sUGxhbmVFbmFibGVkIjp0cnVlLCJNYW5hZ2VkRGF0YVBsYW5lRW5hYmxlZCI6dHJ1ZSwiRW50ZXJwcmlzZUVuYWJsZWQiOnRydWUsIkhBWkxFbmFibGVkIjp0cnVlLCJGSVBTRW5hYmxlZCI6ZmFsc2UsIlBhdGNoUmVsZWFzZXNFbmFibGVkIjp0cnVlfQ.N7PCjE_BdSMWPvc08GI4uOAvC16Kw32nR77sApF77PpVKMTPOTdXfwaW6xFA-pR4uw1-JOzVguV2HYfJuSYL8w
        dataPlaneOperator:
          enabled: true
        controlPlaneOperator:
          enabled: true
        buoyantCloudEnabled: false
    chart: linkerd-buoyant
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-buoyant
