apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-buoyant-controlplane
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  source:
    path: linkerd-operator-argocd/linkerd-buoyant-control-plane
    repoURL: https://github.com/GTRekter/linkerd-operator-argocd.git
    targetRevision: HEAD
  sources: []
  project: default
